name: Bing Wallpaper

permissions: write-all

on:
  schedule:
    - cron: '0 4-10 * * *'
  workflow_dispatch:

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Fetch Bing wallpaper and update README.md
        run: |
          python .github/workflows/fetch_bing_wallpaper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git add old_wallpapers
          git diff-index --quiet HEAD || git commit -m "Update Bing Wallpapers"
          git push
