name: Bing Wallpaper

on:
  schedule:
    - cron: '0 */1 * * *'  # 每1小时运行一次
  workflow_dispatch:

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Fetch Bing wallpaper and update README.md
        run: |
          python .github/workflows/fetch_bing_wallpaper.py

      - name: Commit and push changes
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add private_key.pem
          git config --global user.name "linmew"
          git config --global user.email "jzgflm@gmail.com"
          git remote set-url origin git@github.com:linmew/bingWallpapers.git
          git add README.md
          git add old_wallpapers
          git diff-index --quiet HEAD || git commit -m "Update Bing Wallpapers"
          git push
          rm -f private_key.pem