name: Update Bing Wallpapers

on:
  schedule:
    - cron: "0 * * * *" # 每小时运行一次，您可以根据需要调整此值
  workflow_dispatch:

jobs:
  update_wallpapers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Create wallpapers.json file
      run: |
        touch wallpapers.json

    - name: Get Bing Wallpapers
      run: |
        for i in {0..29}; do
          wallpaper_info=$(curl -sL "https://www.bing.com/HPImageArchive.aspx?format=js&idx=$i&n=1&mkt=en-US" | jq -c '.images[0]')
          wallpaper_url="https://www.bing.com$(echo $wallpaper_info | jq -r '.url')"
          # 检查 README.md 是否已经包含了这个壁纸的 URL
          if ! grep -q "$wallpaper_url" README.md; then
            echo $wallpaper_info >> wallpapers.json
          fi
        done

    - name: Create old_wallpapers folder
      run: |
        mkdir -p old_wallpapers

    - name: Update README
      run: |
        README_FILE="README.md"
        WALLPAPERS_START_TAG="<!-- BING_WALLPAPERS_START -->"
        WALLPAPERS_END_TAG="<!-- BING_WALLPAPERS_END -->"
        OLD_WALLPAPERS_DIR="old_wallpapers"

        # 添加新的壁纸
        echo $WALLPAPERS_START_TAG >> temp.md
        while read -r line; do
          wallpaper_url="https://www.bing.com$(echo $line | jq -r '.url')"
          wallpaper_name="$(echo $line | jq -r '.copyright')"
          wallpaper_date="$(echo $line | jq -r '.enddate')"
          echo "<img src=\"$wallpaper_url\" alt=\"$wallpaper_name\" width=\"300\"><br>$wallpaper_date - $wallpaper_name<br><br>" >> temp.md
        done < wallpapers.json
        echo $WALLPAPERS_END_TAG >> temp.md

        # 将新的壁纸部分添加到README文件
        sed -i "/$WALLPAPERS_START_TAG/,/$WALLPAPERS_END_TAG/{//!d}" $README_FILE
        sed -i "/$WALLPAPERS_START_TAG/r temp.md" $README_FILE

        # 删除临时文件
        rm temp.md wallpapers.json

    - name: Remove duplicates from README.md
      run: |
        README_FILE="README.md"
        WALLPAPERS_START_TAG="<!-- BING_WALLPAPERS_START -->"
                WALLPAPERS_END_TAG="<!-- BING_WALLPAPERS_END -->"

        sed -n "/$WALLPAPERS_START_TAG/,/$WALLPAPERS_END_TAG/p" $README_FILE > wallpapers_section.md
        awk '!seen[$0]++' wallpapers_section.md > wallpapers_section_deduplicated.md

        sed -i "/$WALLPAPERS_START_TAG/,/$WALLPAPERS_END_TAG/{//!d}" $README_FILE
        sed -i "/$WALLPAPERS_START_TAG/r wallpapers_section_deduplicated.md" $README_FILE

        rm wallpapers_section.md wallpapers_section_deduplicated.md

    - name: Commit and push changes
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        eval "$(ssh-agent -s)"
        ssh-add private_key.pem
        git config --global user.name "linmew"
        git config --global user.email "jzgflm@gmail.com"
        git remote set-url origin git@github.com:linmew/bingWallpapers.git
        git add README.md
        git commit -m "Update Bing Wallpapers"
        git push
        rm -f private_key.pem