name: Update Bing Wallpapers

on:
  schedule:
    - cron: "0 * * * *" # 每小时运行一次，您可以根据需要调整此值
  workflow_dispatch:

jobs:
  update_wallpapers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Create wallpapers.json file
      run: |
        touch wallpapers.json

    - name: Get Bing Wallpapers
      run: |
        for i in {0..29}; do
          wallpaper_info=$(curl -sL "https://www.bing.com/HPImageArchive.aspx?format=js&idx=$i&n=1&mkt=en-US" | jq -c '.images[0]')
          wallpaper_url="https://www.bing.com$(echo $wallpaper_info | jq -r '.url')"
          # 检查 README.md 是否已经包含了这个壁纸的 URL
          if ! grep -q "$wallpaper_url" README.md; then
            echo $wallpaper_info >> wallpapers.json
          fi
        done

    - name: Create old_wallpapers folder
      run: |
        mkdir -p old_wallpapers

    - name: Update README
      run: |
        README_FILE="README.md"
        jq -s 'sort_by(.enddate) | reverse' wallpapers.json > sorted_wallpapers.json
        NEW_WALLPAPER=$(head -n 1 sorted_wallpapers.json | jq -c '.[0]')
        OLD_WALLPAPERS_DIR="old_wallpapers"

        if [ -s wallpapers.json ]; then
          # 判断是否有新壁纸，如果有则将新壁纸插入到表格的第一个位置
          if ! grep -q "$(echo $NEW_WALLPAPER | jq -r '.url')" README.md; then
            NEW_WALLPAPER_HTML="<tr><td><img src=\"https://www.bing.com$(echo $NEW_WALLPAPER | jq -r '.url')\" alt=\"$(echo $NEW_WALLPAPER | jq -r '.copyright')\" width=\"100%\"></td></tr>"
            sed -i "2s|^|$NEW_WALLPAPER_HTML|" $README_FILE
          fi

          # 更新表格中的其他壁纸
          INDEX=0
          COUNT=$(grep -c '<td>' $README_FILE)
          while read -r line; do
            if [ $INDEX -eq 0 ]; then
              INDEX=$((INDEX+1))
              continue
            fi
            WALLPAPER_URL="https://www.bing.com$(echo $line | jq -r '.url')"
            WALLPAPER_NAME="$(echo $line | jq -r '.copyright')"
            WALLPAPER_DATE="$(echo $line | jq -r '.enddate')"
            WALLPAPER_HTML="<td><img src=\"$WALLPAPER_URL\" alt=\"$WALLPAPER_NAME\" width=\"100%\"><br>$WALLPAPER_DATE - $WALLPAPER_NAME</td>"
            if (( $INDEX % 3 == 1 )); then
              WALLPAPER_HTML="<tr>$WALLPAPER_HTML"
            elif (( $INDEX % 3 == 0 )); then
              WALLPAPER_HTML="$WALLPAPER_HTML</tr>"
            fi
            # 如果壁纸数量超过 30，将旧壁纸移动到 old_wallpapers 文件夹
            if [ $COUNT -gt 30 ]; then
              OLDEST_WALLPAPER=$(grep -m 1 '<td>' $README_FILE)
              OLDEST_WALLPAPER_URL=$(echo $OLDEST_WALLPAPER | grep -Eo 'src="[^"]+' | cut -d'"' -f2)
              OLDEST_WALLPAPER_DATE=$(echo $OLDEST_WALLPAPER | grep -Eo "<br>([^<]+)" | cut -d'<' -f1 | cut -d'>' -f2)
              OLDEST_WALLPAPER_PATH=$(date -d $OLDEST_WALLPAPER_DATE+%Y/%m/%d)
              mkdir -p $OLD_WALLPAPERS_DIR/$OLDEST_WALLPAPER_PATH
              wget $OLDEST_WALLPAPER_URL -O $OLD_WALLPAPERS_DIR/$OLDEST_WALLPAPER_PATH/$(basename $OLDEST_WALLPAPER_URL)
              # 从README.md中删除旧壁纸
              sed -i "/$(basename $OLDEST_WALLPAPER_URL)/d" $README_FILE
              COUNT=$((COUNT-1))
            fi
            # 将更新的壁纸插入表格中
            sed -i "/<\/table>/i $WALLPAPER_HTML" $README_FILE
            INDEX=$((INDEX+1))
            done < <(jq -c '.[]' sorted_wallpapers.json)

            # 删除临时文件
            rm sorted_wallpapers.json
          fi

    - name: Commit and push changes
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        eval "$(ssh-agent -s)"
        ssh-add private_key.pem
        git config --global user.name "linmew"
        git config --global user.email "jzgflm@gmail.com"
        git remote set-url origin git@github.com:linmew/bingWallpapers.git
        git add README.md
        git commit -m "Update Bing Wallpapers"
        git push
        rm -f private_key.pem